title: ideasmeetings.org
email: kris@ideawave.ca
description: > # this means to ignore newlines until "baseurl:"
  We help each other make our ideas happen. Join us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ideasmeetings.org" # the base hostname & protocol for your site
twitter_username: ideasmeetings
facebook_username: ideasvan
# Build settings
markdown: kramdown
